### PR TITLE
Bump dev version

### PR DESCRIPTION
**Pull request by bjodah**
In response to @raphaelquast question in symengine/symengine.py#188

I believe this needs to pass first:
https://github.com/symengine/symengine-feedstock/pull/4

Let me know if I didn't get it right.

### CODE REVIEW

**Comment by bjodah** [comment]
Huh, this commit seem to have generated a package under the label "broken":

https://anaconda.org/symengine/python-symengine/labels

**Comment by certik** [comment]
Why would that be?

**Comment by isuruf** [comment]
I moved them because of https://github.com/symengine/symengine.py/issues/190. Let's create new ones after https://github.com/symengine/symengine.py/pull/191/files

**Comment by raphaelquast** [comment]
hi, just out of curiosity...
is it now possible to have a dev-version that incorporates the changes (#191 seems to be merged)
or is it more appropriate to wait for a new full release? (if so, when would that approximately be?)

**Comment by isuruf** [comment]
@raphaelquast, there was https://github.com/symengine/python-symengine-feedstock/pull/5 which has #191. You can use `symengine/label/dev` conda channel to get the dev version

**Comment by raphaelquast** [comment]
@isuruf thanks! worked like charm :-)
oh, and by the way... (in case you've overseen it) the broken label is still remaining here: 
https://anaconda.org/symengine/python-symengine

**Pull request merged**
